# Example configuration for the GraphQL plugin

# Enable mock responses for testing
mockEnable: false

# GraphQL schema configuration
schema:
  # Path to the GraphQL schema file
  path: "schema.graphql"
  
  # Enable introspection
  introspection: true

# Logging configuration
log:
  level: "info"
  format: "json"