name: GitHub Actions Status

on:
  workflow_run:
    workflows: ["CI/CD Pipeline", "Feature Branch CI", "Release Pipeline", "Hotfix Pipeline"]
    types: [completed]

jobs:
  update-status:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    steps:
      - name: Update README badges
        uses: actions/github-script@v7
        with:
          script: |
            // This is a placeholder for future badge updates
            console.log('Workflow completed:', github.event.workflow_run.conclusion);
